#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DB_APP_NAME};
    ALTER USER ${DB_APP_NAME} WITH PASSWORD '${DB_APP_PASSWORD}';
    CREATE DATABASE ${DB_APP_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_APP_NAME} TO ${DB_APP_NAME};
EOSQL
