name: Validate

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build & validate
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - run: cd app && make
