name: Build and publish

on:
  push:
    branches: ['*']
    tags: ['v*']

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
      GITHUB_USERNAME: x-access-token
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Ref: ${GIT_REF}"
      - run: | 
          make
        if: startsWith(github.ref, 'refs/heads')
      - run: |
          VERSION=${GIT_REF#refs/tags/} make publish
        if: startsWith(github.ref, 'refs/tags/v')
