name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - run: make
      - run: make test
