name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
      GIT_BRANCH: ${{ github.ref.replace('ref/heads/', '') }}
    steps:
      - uses: actions/checkout@v1
      - run: echo "on branch ${GIT_BRANCH}"
        name: output ${{ env.GIT_BRANCH }}
      - run: make
      - run: make test
