name: Publish Docker Image

on:
  push:
    tags: ["v*"]
    branches: ["docker"]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build & push docker image
        run: |
          REF_NAME=${GITHUB_REF#refs/*/}
          IMAGE_TAG=${REF_NAME/docker/latest} make docker-build docker-push
