name: Publish release

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION=${GIT_REF#refs/tags/} make
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Publish assets
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/lolcatz-backend-${{ github.ref }}-darwin-amd64
          asset_name: lolcatz-backend-${{ github.ref }}-darwin-amd64
          asset_content_type: application/octet-stream
