name: Validate

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Integration tests
    env:
      # AWS SDK requires some kind of credentials, but localstack doesn't validate them
      AWS_ACCESS_KEY_ID: bogus 
      AWS_SECRET_ACCESS_KEY: bogus
    steps:
      - uses: actions/checkout@v1
      - run: cd app && make test

    services:
      postgres:
        image: postgres:13.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testdb
          POSTGRES_PASSWORD: testdb
          POSTGRES_DB: testdb

      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3
